sudo: false
language: ruby
rvm:
- 2.4.0
before_install:
- openssl aes-256-cbc -K $encrypted_beae48297d74_key -iv $encrypted_beae48297d74_iv -in deploy_key.enc -out deploy_key -d
install:
- gem install bundle
- bundle install
script:
- ./deploy-script.sh
env:
  global:
  - ENCRYPTION_LABEL: "beae48297d74"
  - COMMIT_AUTHOR_EMAIL: "pastorsj@rose-hulman.edu"
